finalProject/account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


app_name = "account"

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('logout/confirmation/', views.LogoutPopup, name='logout_popup'),
    path('redirect/home/', views.RedirectHome, name='redirect_home'),
    path('signup/shipper/', views.ShipperSignUpView.as_view(), name='shipper_signup'),
    path('signup/carrier/', views.CarrierSignUpView.as_view(), name='carrier_signup'),
    #path('password/reset/', views.CustomPasswordResetView.as_view(), name='reset_password'),
    #path('password/reset/done/', views.CustomPasswordResetDoneView.as_view(), name='reset_password_done'),
    #path('password/reset/confirm/<uidb64>/<token>', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #path('password/reset/complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

finalProject/carrier/urls.py
from django.urls import path

from . import views

app_name = "carrier"

urlpatterns = [
    path('home/', views.CarrierHome.as_view(), name='home'),
    path('home/load/accept/<int:pk_load>/', views.AcceptLoad.as_view(), name='accept_load'),
    path('home/load/reject/<int:pk_load>/', views.RejectLoad.as_view(), name='reject_load'),
    path('home/load/drop/<int:pk_load>/', views.DropLoad.as_view(), name='drop_load'),
]

finalProject/urls.py
from django.contrib import admin
from django.urls import path, include

from finalProject.core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('account/', include('finalProject.account.urls'), name='account'),
    path('api/', include('finalProject.api.urls'), name="api"),
    path('carrier/', include('finalProject.carrier.urls'), name='carrier'),
    path('shipper/', include('finalProject.shipper.urls'), name='shipper'),


]

finalProject/carrier/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from finalProject.account.models import User
from finalProject.shipper.models import Load


class CarrierUser(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='carrier_user')
    MC_number = models.IntegerField(
        _('MC number'), null=False, blank=False, unique=True)

    def __str__(self):
        return "carrier id: {}, User id: {}, Name: {}, MC Number: {}".format(
            self.pk, self.user.pk, self.user.first_name, self.MC_number
        )


class RejectedLoad(models.Model):
    load = models.ForeignKey(Load, on_delete=models.CASCADE)
    carrier = models.ForeignKey(CarrierUser, on_delete=models.CASCADE)

    def __str__(self):
        return "Load: {}, Carrier: {}".format(self.load, self.carrier)

finalProject/carrier/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, UpdateView
from django.db import transaction
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.core.mail import send_mail
from django.template.loader import render_to_string
from finalProject.carrier.models import RejectedLoad, CarrierUser
from finalProject.shipper.models import Load
from finalProject.settings import DEFAULT_FROM_EMAIL


class CarrierHome(LoginRequiredMixin, ListView):
    template_name = 'carrier_home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['available_loads'] = self.available_loads
        context['accepted_loads'] = self.accepted_loads
        context['rejected_loads'] = self.rejected_loads
        return context

    def get_queryset(self):
        carrier = CarrierUser.objects.get(user_id=self.request.user.id)
        rej_loads = RejectedLoad.objects.filter(carrier=carrier)
        self.available_loads = Load.objects.filter(status='available').exclude(
            id__in=rej_loads.values('load_id'))
        self.accepted_loads = Load.objects.filter(
            status='accepted', carrier=carrier)
        self.rejected_loads = Load.objects.filter(id__in=rej_loads.values('load_id'))


class AcceptLoad(LoginRequiredMixin, UpdateView):
    model = Load
    template_name = 'carrier_home.html'
    success_url = reverse_lazy('carrier:home')

    @transaction.atomic
    def get(self, request, *args, **kwargs):
        try:
            load = Load.objects.get(pk=kwargs['pk_load'], status='available')
        except:
            messages.error(request, 'ERROR: This load is not available anymore')
            return redirect('carrier:home')

        carrier = CarrierUser.objects.get(user_id=request.user.id)
        load.accept_load(carrier)
        messages.success(request, 'Load accepted successfully')
        '''
        email_subject = 'Your load was accepted'
        html_message = render_to_string('email_message_load_accepted.html', {'load': load})
        from_email = DEFAULT_FROM_EMAIL
        to_email = [load.shipper.user.email]
        send_mail(email_subject, html_message, from_email, to_email)
        '''
        return redirect('carrier:home')


class RejectLoad(LoginRequiredMixin, UpdateView):
    model = Load
    template_name = 'carrier_home.html'
    success_url = reverse_lazy('carrier:home')

    @transaction.atomic
    def get(self, request, *args, **kwargs):
        try:
            load = Load.objects.get(pk=kwargs['pk_load'], status='available')
        except:
            messages.error(request, 'ERROR: This load is not available anymore')
            return redirect('carrier:home')

        carrier = CarrierUser.objects.get(user_id=request.user.id)
        RejectedLoad.objects.create(load=load, carrier=carrier)
        messages.success(request, 'Load rejected successfully')
        return redirect('carrier:home')


class DropLoad(LoginRequiredMixin, UpdateView):
    model = Load
    template_name = 'carrier_home.html'
    success_url = reverse_lazy('carrier:home')

    @transaction.atomic
    def get(self, request, *args, **kwargs):
        try:
            carrier = CarrierUser.objects.get(user_id=request.user.id)
            load = Load.objects.get(pk=kwargs['pk_load'], status='accepted', carrier=carrier)
        except:
            messages.error(request, 'ERROR: This load is not accepted by you')
            return redirect('carrier:home')

        load.drop_load()
        RejectedLoad.objects.create(load=load, carrier=carrier)
        messages.success(request, 'Load dropped successfully')
        '''
        email_subject = 'Your load was dropped'
        html_message = render_to_string('email_message_load_dropped.html', {'load': load})
        from_email = DEFAULT_FROM_EMAIL
        to_email = [load.shipper.user.email]
        send_mail(email_subject, html_message, from_email, to_email)
        '''
        return redirect('carrier:home')

finalProject/carrier/templates/carrier_abas.html
{% extends 'base.html' %}

{% block title %} Carrier's Page {% endblock title %} 

{% block navbar-options %} 
<li><a title="logout" class="logout-popup-button" >Logout</a></li>
{% endblock navbar-options%}

{% block content %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>

<br/>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.level_tag}}" role="alert">
   <ul class="messages">
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
   </ul>
</div>
{% endfor %}
{% endif %}

<br/>
<br/>
<br/>

<ul class="nav nav-pills" id="pills-tab" style="width:80%; margin: 0px auto; ">
   <li class="active"><a href="#tab1" data-toggle="tab">Available loads</a></li>
   <li><a href="#tab2" data-toggle="tab">Accepted loads</a></li>
   <li><a href="#tab3" data-toggle="tab">Rejected loads</a></li>
</ul>
<div class="tab-content">
    <div class="tab-pane active" id="tab1" style="width:80%; margin: 0px auto;">
      <table id="tableAvailable" class="table " >
            <thead style="color:white; background-color: #4c4c4c;">
            <tr >
               <th>Pickup Date</th>
               <th>Ref.</th>
               <th>Origin City</th>
               <th>Destination City</th>
               <th>Price</th>
               <th>Shipper</th>
               <th> </th>
            </tr>
            </thead>
            <tbody>
            {% for load in available_loads %}
            <tr>
               <td>{{load.pickup_date}}</td>
               <td>{{load.ref}}</td>
               <td>{{load.origin_city}}</td>
               <td>{{load.destination_city}}</td>
               <td>${{load.carrier_price|floatformat:2}}</td>
               <td>{{load.shipper.user.get_full_name}}</td>
               <td style="text-align: center;">
                  <a class="btn " href="{% url 'carrier:reject_load' pk_load=load.pk %}"> Reject </a>
                  <a class="btn btn-success " href="{% url 'carrier:accept_load' pk_load=load.pk %}"> Accept </a>
               </td>
               
            </tr>
            {% endfor %}
            </tbody>
         </table>
         <br/> <br/> <br/>
    </div>
    <div class="tab-pane" id="tab2" style="width:80%; margin: 0px auto;">
      <table id="tableAccepted" class="table " >
            <thead style="color:white; background-color: #4c4c4c;">
            <tr>
               <th>Pickup Date</th>
               <th>Ref.</th>
               <th>Origin City</th>
               <th>Destination City</th>
               <th>Price</th>
               <th>Shipper</th>
               <th> </th>
            </tr>
            </thead>
            <tbody>
            {% for load in accepted_loads %}
            <tr>
               <td>{{load.pickup_date}}</td>
               <td>{{load.ref}}</td>
               <td>{{load.origin_city}}</td>
               <td>{{load.destination_city}}</td>
               <td>${{load.carrier_price|floatformat:2 }}</td>
               <td>{{load.shipper.user.get_full_name}}</td>
               <td style="text-align: center;"><a class="btn " href="{% url 'carrier:drop_load' pk_load=load.pk %}"> Drop </a></td>
            </tr>
            {% endfor %}
            </tbody>
         </table>
         <br/> <br/> <br/>
    </div>
    <div class="tab-pane" id="tab3" style="width:80%; margin: 0px auto;">
      <table id="tableRejected" class="table " >
            <thead style="color:white; background-color: #4c4c4c;">
            <tr>
               <th>Pickup Date</th>
               <th>Ref.</th>
               <th>Origin City</th>
               <th>Destination City</th>
               <th>Price</th>
               <th>Shipper</th>
            </tr>
            </thead>
            <tbody>
            {% for load in rejected_loads %}
            <tr>
               <td>{{load.pickup_date}}</td>
               <td>{{load.ref}}</td>
               <td>{{load.origin_city}}</td>
               <td>{{load.destination_city}}</td>
               <td>${{load.carrier_price|floatformat:2}}</td>
               <td>{{load.shipper.user.get_full_name}}</td>
            </tr>
            {% endfor %}
            </tbody>
         </table>
         <br/> <br/> <br/>
    </div>
</div>

<script>
   $(document).ready( function () {
      $('#tableAvailable').DataTable({
         "paging": false,
         "info": false,
         "language": {
            "emptyTable": "There are no available loads"
         }
      });
      $('#tableAccepted').DataTable({
         "paging": false,
         "info": false,
         "language": {
            "emptyTable": "There are no accepted loads"
         }
      });
      $('#tableRejected').DataTable({
         "paging": false,
         "info": false,
         "language": {
            "emptyTable": "There are no rejected loads"
         }
      });
   } );
</script>

<section>

   <div class="modal fade" tabindex="-1" role="dialog" id="modal">
      <div class="modal-dialog" role="document">
         <div class="modal-content">
         </div>
      </div>
   </div>

   <script type="text/javascript">
      $(document).ready(function() {
          $(".logout-popup-button").modalForm({
              formURL: "{% url 'account:logout_popup' %}" 
          });
      });
   </script>

</section>

{% endblock %}

finalProject/carrier/templates/carrier_home.html
{% extends 'base.html' %}

{% block title %} Carrier's Page {% endblock title %}

{% block navbar-options %}
<li><a title="logout" class="logout-popup-button">Logout</a></li>
{% endblock navbar-options%}

{% block content %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>

<br/>

{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.level_tag}} message" role="alert" style="width:77%; margin: 0px auto;">
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
            {{ message }} <a href="#" class="del-msg">&times;</a>
        </li>
    </div>
    {% endfor %}
{% endif %}

<br/>

<ul class="nav nav-pills table-size" id="pills-tab">
    <li class="active"><a href="#tab1" data-toggle="tab">Available loads</a></li>
    <li><a href="#tab2" data-toggle="tab">Accepted loads</a></li>
    <li><a href="#tab3" data-toggle="tab">Rejected loads</a></li>
</ul>
<div class="tab-content">
    <div class="tab-pane table-size active" id="tab1">
        <table id="tableAvailable" class="table ">
            <thead class="table-head">
            <tr>
                <th>PICK UP</th>
                <th>REF.#</th>
                <th>ORIGIN</th>
                <th>DESTINATION</th>
                <th>PRICE</th>
                <th>SHIPPER</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for load in available_loads %}
            <tr>
                <td>{{load.pickup_date}}</td>
                <td>{{load.ref}}</td>
                <td>{{load.origin_city}}</td>
                <td>{{load.destination_city}}</td>
                <td>${{load.carrier_price|floatformat:2}}</td>
                <td>{{load.shipper.user.get_full_name}}</td>
                <td style="text-align: center;">
                    <a class="btn " href="{% url 'carrier:reject_load' pk_load=load.pk %}"> Reject </a>
                    <a class="btn btn-success " href="{% url 'carrier:accept_load' pk_load=load.pk %}"> Accept </a>
                </td>

            </tr>
            {% endfor %}
            </tbody>
        </table>
        <br/> <br/> <br/>
    </div>
    <div class="tab-pane table-size" id="tab2">
        <table id="tableAccepted" class="table">
            <thead class="table-head">
            <tr>
                <th>PICK UP</th>
                <th>REF.#</th>
                <th>ORIGIN</th>
                <th>DESTINATION</th>
                <th>PRICE</th>
                <th>SHIPPER</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for load in accepted_loads %}
            <tr>
                <td>{{load.pickup_date}}</td>
                <td>{{load.ref}}</td>
                <td>{{load.origin_city}}</td>
                <td>{{load.destination_city}}</td>
                <td>${{load.carrier_price|floatformat:2 }}</td>
                <td>{{load.shipper.user.get_full_name}}</td>
                <td style="text-align: center;"><a class="btn " href="{% url 'carrier:drop_load' pk_load=load.pk %}">
                    Drop </a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <br/> <br/> <br/>
    </div>
    <div class="tab-pane table-size" id="tab3">
        <table id="tableRejected" class="table ">
            <thead class="table-head">
            <tr>
                <th>PICK UP</th>
                <th>REF.#</th>
                <th>ORIGIN</th>
                <th>DESTINATION</th>
                <th>PRICE</th>
                <th>SHIPPER</th>
            </tr>
            </thead>
            <tbody>
            {% for load in rejected_loads %}
            <tr>
                <td>{{load.pickup_date}}</td>
                <td>{{load.ref}}</td>
                <td>{{load.origin_city}}</td>
                <td>{{load.destination_city}}</td>
                <td>${{load.carrier_price|floatformat:2}}</td>
                <td>{{load.shipper.user.get_full_name}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <br/> <br/> <br/>
    </div>
</div>

<script>
   $(document).ready( function () {
      $('#tableAvailable').DataTable({
         "paging": false,
         "info": false,
         "language": {
            "emptyTable": "There are no available loads"
         }
      });
      $('#tableAccepted').DataTable({
         "paging": false,
         "info": false,
         "language": {
            "emptyTable": "There are no accepted loads"
         }
      });
      $('#tableRejected').DataTable({
         "paging": false,
         "info": false,
         "language": {
            "emptyTable": "There are no rejected loads"
         }
      });
   } );

</script>

<section>

    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            </div>
        </div>
    </div>

    <script type="text/javascript">
      $(document).ready(function() {
          $(".logout-popup-button").modalForm({
              formURL: "{% url 'account:logout_popup' %}" 
          });
      });

    </script>

    <script>
      $(document).ready(function() {
        // messages timeout for 10 sec 
        setTimeout(function() {
            $('.message').fadeOut('slow');
        }, 10000); // <-- time in milliseconds, 1000 =  1 sec

        // delete message
        $('.del-msg').live('click',function(){
            $('.del-msg').parent().parent().attr('style', 'display:none;');
        })
      });
    </script>

</section>

{% endblock %}

finalProject/carrier/templates/email_message_load_accepted.html
{% autoescape off %}

Dear {{ load.shipper.user.get_full_name }},

The following load was ACCEPTED by {{ load.carrier.user.get_full_name }}:

Pickup Date: {{ load.pickup_date }}
REF. : {{ load.ref }}
Origin City: {{ load.origin_city }}
Destination City: {{ load.destination_city }}
Price: {{ load.price }}


Sincerely,
Squad 1
{% endautoescape %}

finalProject/carrier/templates/email_message_load_dropped.html
{% autoescape off %}

Dear {{ load.shipper.user.get_full_name }},

The following load was DROPPED by {{ load.carrier.user.get_full_name }}:

Pickup Date: {{ load.pickup_date }}
REF. : {{ load.ref }}
Origin City: {{ load.origin_city }}
Destination City: {{ load.destination_city }}
Price: {{ load.price }}

This load is now available for other Carriers.
You will be notified if someone else accepts it.

Sincerely,
Squad 1
{% endautoescape %}