finalProject/account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


app_name = "account"

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('logout/confirmation/', views.LogoutPopup, name='logout_popup'),
    path('redirect/home/', views.RedirectHome, name='redirect_home'),
    path('signup/shipper/', views.ShipperSignUpView.as_view(), name='shipper_signup'),
    path('signup/carrier/', views.CarrierSignUpView.as_view(), name='carrier_signup'),
    #path('password/reset/', views.CustomPasswordResetView.as_view(), name='reset_password'),
    #path('password/reset/done/', views.CustomPasswordResetDoneView.as_view(), name='reset_password_done'),
    #path('password/reset/confirm/<uidb64>/<token>', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #path('password/reset/complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

finalProject/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from finalProject.api import views

app_name = "api"

urlpatterns = [
    path('token/', views.getToken, name="get_token"),
    path('carrier/loads/available/', views.CarrierAvailableLoads.as_view({'get': 'list'}),
         name='list_carrier_available'),
    path('carrier/loads/accepted/', views.CarrierAcceptedLoads.as_view({'get': 'list'}), name='list_carrier_accepted'),
    path('carrier/loads/rejected/', views.CarrierRejectedLoads.as_view({'get': 'list'}), name='list_carrier_rejected'),
    path('carrier/load/accept/<int:pk_load>/', views.carrierAccept, name='accept_load'),
    path('carrier/load/reject/<int:pk_load>/', views.carrierReject, name='reject_load'),
    path('carrier/load/drop/<int:pk_load>/', views.carrierDrop, name='drop_load'),
    path('shipper/loads/available/', views.ShipperAvailableLoads.as_view({'get': 'list'}),
         name='list_shipper_available'),
    path('shipper/loads/accepted/', views.ShipperAcceptedLoads.as_view({'get': 'list'}), name="list_shipper_accepted"),
    path('shipper/load/post/', views.shipperPostLoad, name="post_load"),
    path('documentation/', views.apiDocumentation, name="docs"),

]

urlpatterns = format_suffix_patterns(urlpatterns)

finalProject/urls.py
from django.contrib import admin
from django.urls import path, include

from finalProject.core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('account/', include('finalProject.account.urls'), name='account'),
    path('api/', include('finalProject.api.urls'), name="api"),
    path('carrier/', include('finalProject.carrier.urls'), name='carrier'),
    path('shipper/', include('finalProject.shipper.urls'), name='shipper'),


]

finalProject/api/models.py
from django.db import models

# After we have to reorganized this class to app load

finalProject/api/views.py
from django.contrib.auth import authenticate
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from rest_framework import viewsets
from rest_framework.authentication import TokenAuthentication
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.response import Response
from rest_framework.status import HTTP_400_BAD_REQUEST, HTTP_404_NOT_FOUND, HTTP_200_OK

from finalProject.api.permissions import IsCarrier, IsShipper
from finalProject.api.serializers import LoadSerializer
from finalProject.carrier.models import CarrierUser, RejectedLoad
from finalProject.shipper.models import Load, ShipperUser


@csrf_exempt
@api_view(["POST"])
@permission_classes((AllowAny,))
def getToken(request):
    email = request.data.get("email")
    password = request.data.get("password")
    if email is None or password is None:
        return Response({'error': 'Please provide both email and password'},
                        status=HTTP_400_BAD_REQUEST)
    user = authenticate(email=email, password=password)
    if not user:
        return Response({'error': 'Invalid Credentials'},
                        status=HTTP_404_NOT_FOUND)
    token, _ = Token.objects.get_or_create(user=user)
    return Response({'token': token.key},
                    status=HTTP_200_OK)


class CarrierAvailableLoads(viewsets.ReadOnlyModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated, IsCarrier,)
    serializer_class = LoadSerializer

    def get_queryset(self):
        carrier = CarrierUser.objects.get(user_id=self.request.user.id)
        rej_loads = RejectedLoad.objects.filter(carrier=carrier)
        available_loads = Load.objects.filter(status='available').exclude(
            id__in=rej_loads.values('load_id'))
        return available_loads


class CarrierAcceptedLoads(viewsets.ReadOnlyModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated, IsCarrier,)
    serializer_class = LoadSerializer

    def get_queryset(self):
        carrier = CarrierUser.objects.get(user_id=self.request.user.id)
        accepted_loads = Load.objects.filter(
            status='accepted', carrier=carrier)
        return accepted_loads


class CarrierRejectedLoads(viewsets.ReadOnlyModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated, IsCarrier,)
    serializer_class = LoadSerializer

    def get_queryset(self):
        carrier = CarrierUser.objects.get(user_id=self.request.user.id)
        rej_loads = RejectedLoad.objects.filter(carrier=carrier)
        rejected_loads = Load.objects.filter(id__in=rej_loads.values('load_id'))
        return rejected_loads


@api_view(["PUT"])
@permission_classes((IsAuthenticated, IsCarrier,))
def carrierAccept(request, pk_load):
    try:
        load = Load.objects.get(pk=pk_load, status='available')
    except:
        return Response({'error': 'Load not found or Load not available'},
                        status=HTTP_404_NOT_FOUND)

    carrier = CarrierUser.objects.get(user_id=request.user.id)
    load.accept_load(carrier)
    return Response({'success': 'Load accepted successfully'},
                    status=HTTP_200_OK)


@api_view(["PUT"])
@permission_classes((IsAuthenticated, IsCarrier,))
def carrierReject(request, pk_load):
    try:
        load = Load.objects.get(pk=pk_load, status='available')
    except:
        return Response({'error': 'Load not found or Load not available'},
                        status=HTTP_404_NOT_FOUND)

    carrier = CarrierUser.objects.get(user_id=request.user.id)
    RejectedLoad.objects.create(load=load, carrier=carrier)
    return Response({'success': 'Load rejected successfully'},
                    status=HTTP_200_OK)


@api_view(["PUT"])
@permission_classes((IsAuthenticated, IsCarrier,))
def carrierDrop(request, pk_load):
    try:
        carrier = CarrierUser.objects.get(user_id=request.user.id)
        load = Load.objects.get(pk=pk_load, status='accepted', carrier=carrier)
    except:
        return Response({'error': 'Load not found or Load is not accepted by you'},
                        status=HTTP_404_NOT_FOUND)

    load.drop_load()
    RejectedLoad.objects.create(load=load, carrier=carrier)
    return Response({'success': 'Load dropped successfully'},
                    status=HTTP_200_OK)


class ShipperAvailableLoads(viewsets.ReadOnlyModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated, IsShipper,)
    serializer_class = LoadSerializer

    def get_queryset(self):
        shipper = ShipperUser.objects.get(user_id=self.request.user.id)
        available_loads = Load.objects.filter(status='available', shipper=shipper)
        return available_loads


class ShipperAcceptedLoads(viewsets.ReadOnlyModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated, IsShipper,)
    serializer_class = LoadSerializer

    def get_queryset(self):
        shipper = ShipperUser.objects.get(user_id=self.request.user.id)
        accepted_loads = Load.objects.filter(status='accepted', shipper=shipper)
        return accepted_loads


@api_view(["POST"])
@permission_classes((IsAuthenticated, IsShipper,))
def shipperPostLoad(request):
    serializer = LoadSerializer(data=request.data)

    if serializer.is_valid():
        shipper = ShipperUser.objects.get(user_id=request.user.id)
        serializer.save(shipper=shipper)
        return Response({'success': 'Load posted successfully'},
                        status=HTTP_200_OK)
    return Response(serializer.errors,
                    status=HTTP_400_BAD_REQUEST)


def apiDocumentation(request):
    return render(request, 'index_api.html')

finalProject/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

finalProject/core/templates/partials/_api.html
<section id="api" class="section green">
   <div class="container" style="width: 80%;">
      <div id="left" style="float:left; width: 40%;">
         <h4 style="text-align: left;">API</h4>
         <h5>
            <p>
               Our API allows <strong>Shippers</strong> to: 
            </p>
         </h5>
         <h5>
            <p>
            <ul style="padding-left: 40px; color: white;">
               <li>Post Loads</li>
               <li>Get Available and Accepted Loads Information</li>
            </ul>
            </p>
         </h5>
         <h5>
            <p>
               Our API allows <strong>Carriers</strong> to: 
            </p>
         </h5>
         <h5>
            <p>
            <ul style="padding-left: 40px; color: white;">
               <li>Accept, Reject and Drop Loads</li>
               <li>Get Available, Accepted and Rejected Loads Information</li>
            </ul>
            </p>
         </h5>
         <br>
         <br>
         <div style="z-index: 1; position:relative;">
            <a class="btn"  href="{% url 'api:docs' %}" target="_blank">
            <strong>API Full Documentation</strong></a>
         </div>
      </div>
      <div id="right" style="float:right; width: 55%; height:470px; background-color: white; border-radius: 20px;">
         <br>
         <ul class="nav nav-pills" id="pills-tab" style="width:90%; margin: 0px auto;">
            <li class="active" style="width:50%; text-align:center; "><a href="#tab1" data-toggle="tab" style="border-radius: 10px;"> <strong>PYTHON </strong></a></li>
            <li style="width:50%; text-align:center;"><a href="#tab2" data-toggle="tab" style="border-radius: 10px;"> <strong>BASH </strong></a></li>
         </ul>
         <div class="tab-content">
            <div class="tab-pane active" id="tab1" style="width:90%; margin: 0px auto;">
               <div>
                  <br>
                  <pre style="background-color: white; border-style: none;">import requests
url = "http://loadsmart-aceleradev.herokuapp.com/api/shipper/load/post/"

load = {
          "pickup_date": "2019-09-13",
          "ref": 3550,
          "origin_city": "Houston",
          "destination_city": "San Diego",
          "price": 1000
        }

headers = {'Authorization': 'Token 09211697a0acc58e598f18f13d6b1cd73ebd91e6'}

response = requests.post(url, json=load, headers=headers)
print(response.content)</pre>
               </div>
            </div>
            <div class="tab-pane" id="tab2" style="width:90%; margin: 0px auto;">
               <div>
                  <br>
                  <pre style="background-color: white; border-style: none;">curl -X POST \
    -H "Authorization: Token 09211697a0acc58e598f18f13d6b1cd73ebd91e6" \ 
    -H "Content-Type: application/json" \ 
    -d "{ 
         "pickup_date":"2019-09-13",
         "ref":"3550",
         "origin_city":"Houston",
         "destination_city":"San Diego",
         "price":1000
        }" \
    http://loadsmart-aceleradev.herokuapp.com/api/shipper/load/post/ </pre>
               </div>
               <br>
            </div>
         </div>
      </div>
   </div>
</section>

finalProject/core/templates/partials/_header.html
{% load static %}

<div id="header-wrapper" class="header-slider">
    <video autoplay muted loop id="hero-video" poster="{% static 'videos/Road-Tripping.jpg' %}">
        <source src="{% static 'videos/Road-Tripping.mp4' %}" type="video/mp4">
    </video>
    <header class="clearfix">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <!-- start slider -->
                     <div id="main-flexslider" class="flexslider">
                        <ul class="slides">
                            <li>
                                <p class="home-slide-content">
                                    <strong>LoadSmart Women </strong>
                                </p>
                            </li>
                            <li>
                                <p class="home-slide-content">
                                    <strong> AceleraDev </strong>
                                </p>
                            </li>
                        </ul>
                    </div>
                    <!-- end slider -->
                </div>
            </div>
            <div class="row">
                <div class="span12">
                    <div class="span3 offset4">
                        <a href="#api" class="btn btn-success">Learn about our API</a>
                    </div>
                </div>
            </div>
        </div>
    </header>
</div>

finalProject/core/templates/partials/_navbar.html
<li><a href="{% url 'api:docs' %}" target="_blank"><i class="icon-book icon-white"></i> API</a></li>
{% if user.is_authenticated %}
    <li><a href="{% url 'account:redirect_home' %}"><i class="icon-home icon-white"></i> Homepage</a></li>
    <li><a class="logout-popup-button" ><i class="icon-user icon-white"></i> Logout</a></li>
{% else %}
    <li><a class="shipper-signup-popup-button" ><i class="icon-briefcase icon-white"></i> Become a Shipper</a></li>
    <li><a class="carrier-signup-popup-button" ><i class="icon-road icon-white"></i> Become a Carrier</a></li>
    <li><a class="login-popup-button" ><i class="icon-user icon-white"></i> Login</a></li>
{% endif %}

finalProject/core/templates/partials/_popups.html
<section>
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
      <div class="modal-dialog" role="document">
         <div class="modal-content">
         </div>
      </div>
   </div>

   <script type="text/javascript" >
      $(document).ready(function() {
          $(".login-popup-button").modalForm({
              formURL: "{% url 'account:login' %}"
          });
          $(".shipper-signup-popup-button").modalForm({
              formURL: "{% url 'account:shipper_signup' %}"
          });
          $(".carrier-signup-popup-button").modalForm({
              formURL: "{% url 'account:carrier_signup' %}"
          });
          $(".logout-popup-button").modalForm({
              formURL: "{% url 'account:logout_popup' %}"
          });
      });
   </script>
</section>

finalProject/core/templates/partials/_spacer.html
<section class="spacer green">
    <div class="container">
        <div class="row">
            <div class="span12 alignright flyLeft">
                <h1 class="large about-loadsmart" >
                    Loadsmart is a New York company that facilitates how shippers and freight brokers find the right carriers to move their shipments.
                </h1>
            </div>
        </div>
    </div>
</section>

finalProject/core/templates/partials/_team.html
{% load static %}

<section id="team" class="section">
    <div class="container">
        <h4>Our Squad</h4>
        <div class="row span12">
            <div class="span3 offset1 flyIn">
                <div class="people">
                    <img class="team-thumb img-circle" src="{% static 'img/team/isabela.png' %}" alt=""/>
                    <h3>Isabela Eifert</h3>
                    <p>
                        Back-end developer
                    </p>
                </div>
            </div>
            <div class="span3 flyIn">
                <div class="people">
                    <img class="team-thumb img-circle" src="{% static 'img/team/aline.png' %}" alt=""/>
                    <h3>Aline Kraemer</h3>
                    <p>
                        Back-end developer
                    </p>
                </div>
            </div>
            <div class="span3 flyIn">
                <div class="people">
                    <img class="team-thumb img-circle" src="{% static 'img/team/ester.png' %}" alt=""/>
                    <h3> Ester Fogaça</h3>
                    <p>
                        Back-end developer
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>