finalProject/account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


app_name = "account"

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('logout/confirmation/', views.LogoutPopup, name='logout_popup'),
    path('redirect/home/', views.RedirectHome, name='redirect_home'),
    path('signup/shipper/', views.ShipperSignUpView.as_view(), name='shipper_signup'),
    path('signup/carrier/', views.CarrierSignUpView.as_view(), name='carrier_signup'),
    #path('password/reset/', views.CustomPasswordResetView.as_view(), name='reset_password'),
    #path('password/reset/done/', views.CustomPasswordResetDoneView.as_view(), name='reset_password_done'),
    #path('password/reset/confirm/<uidb64>/<token>', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #path('password/reset/complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

finalProject/shipper/urls.py
from django.urls import path

from finalProject.shipper.views import ShipperView, PostLoadView, EditPriceView, CancelLoadView

app_name = "shipper"

urlpatterns = [
    path('home/', ShipperView.as_view(), name="home"),
    path('home/load/post/', PostLoadView.as_view(), name="post_load"),
    path('home/load/edit_price/<int:pk>', EditPriceView.as_view(), name='edit_price'),
    path('home/load/cancel/<int:pk>', CancelLoadView.as_view(), name='cancel_load'),
]

finalProject/urls.py
from django.contrib import admin
from django.urls import path, include

from finalProject.core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('account/', include('finalProject.account.urls'), name='account'),
    path('api/', include('finalProject.api.urls'), name="api"),
    path('carrier/', include('finalProject.carrier.urls'), name='carrier'),
    path('shipper/', include('finalProject.shipper.urls'), name='shipper'),


]

finalProject/shipper/models.py
from django.db import models

from finalProject.account.models import User


class ShipperUser(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='shipper_user')

    class Meta:
        verbose_name = 'Shipper'
        verbose_name_plural = 'Shippers'

    def __str__(self):
        return "shipper id: {}, user id: {}, Name: {}".format(
            self.pk, self.user.pk, self.user.first_name
        )


class Load(models.Model):
    pickup_date = models.DateField()
    ref = models.CharField(max_length=50)
    origin_city = models.CharField(max_length=500)
    destination_city = models.CharField(max_length=500)
    price = models.FloatField()
    status = models.CharField(max_length=50, default="available")
    suggested_price = models.FloatField(null=True)
    carrier = models.ForeignKey('carrier.CarrierUser', on_delete=models.CASCADE, blank=True, null=True)
    shipper = models.ForeignKey(ShipperUser, on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name = 'Load'
        verbose_name_plural = 'Loads'

    def accept_load(self, carrier):
        self.status = 'accepted'
        self.carrier = carrier
        self.save()

    def drop_load(self):
        self.status = 'available'
        self.carrier = None
        self.save()

    def carrier_price(self):
        return round(self.price * 0.95, 2)

    def __str__(self):
        return "Pickup date: {}, REF: {}, Origin City: {}, Destination city: {}, Price: {}, Carrier: {}, Shipper: {}".format(
            self.pickup_date, self.ref, self.origin_city, self.destination_city,
            self.price, self.carrier, self.shipper)

finalProject/shipper/forms.py
import datetime

from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from django import forms
from django.core.exceptions import ValidationError
from django.forms import DateInput, TextInput

from finalProject.shipper.models import Load


def priceValidation(price):
    if price <= 0:
        raise forms.ValidationError("Price should be positive")
    if len(str(price).split('.')[1]) >= 3:
        raise forms.ValidationError("Price should have up to 2 decimal places")
    return price


class LoadForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    suggested_price = forms.FloatField(required=False, widget=forms.TextInput(
        attrs={'id': 'suggested_price_id', 'readonly': 'readonly'}))

    class Meta:
        model = Load
        fields = ['pickup_date', 'ref', 'origin_city',
                  'destination_city', 'price', 'suggested_price']
        widgets = {
            'pickup_date': DateInput(attrs={'type': 'date'}),
            'origin_city': TextInput(attrs={'id': 'origin_city_id'}),
            'destination_city': TextInput(attrs={'id': 'destination_city_id'}),
        }

    def clean_suggested_price(self):
        suggested_price = self.cleaned_data.get('suggested_price')
        if suggested_price is None or '':
            raise forms.ValidationError(
                "There are no road between origin and destination cities ")
        return suggested_price

    def clean_price(self):
        price = self.cleaned_data.get('price')
        return priceValidation(price)

    def clean_pickup_date(self):
        pickup_date = self.cleaned_data.get('pickup_date')
        if pickup_date < datetime.date.today():
            raise ValidationError('You can\'t use a past date for a new load.')
        return pickup_date


class UpdatePriceForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    suggested_price = forms.FloatField(required=False, disabled=True)
    ref = forms.CharField(required=False, disabled=True)

    class Meta:
        model = Load
        fields = ['ref', 'price', 'suggested_price']

    def clean_price(self):
        price = self.cleaned_data.get('price')
        return priceValidation(price)

finalProject/shipper/views.py
from bootstrap_modal_forms.mixins import PassRequestMixin
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import ListView
from django.core.mail import send_mail
from django.template.loader import render_to_string

from finalProject.shipper.forms import LoadForm, UpdatePriceForm
from finalProject.shipper.models import ShipperUser
from .models import Load
from finalProject.settings import DEFAULT_FROM_EMAIL


class ShipperView(LoginRequiredMixin, ListView):
    template_name = 'shipper_home.html'
    context_object_name = 'loads'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['api_key'] = settings.GOOGLE_API_KEY
        return context

    def get_queryset(self):
        shipper = ShipperUser.objects.get(user_id=self.request.user.id)
        return Load.objects.filter(shipper=shipper)


class PostLoadView(LoginRequiredMixin, PassRequestMixin, SuccessMessageMixin, generic.CreateView):
    template_name = 'post_load.html'
    form_class = LoadForm
    success_message = 'Success: Load was posted.'
    success_url = reverse_lazy('shipper:home')

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.shipper = ShipperUser.objects.get(user_id=self.request.user.id)
        super().form_valid(form)
        return redirect('shipper:home')


class EditPriceView(PassRequestMixin, SuccessMessageMixin, generic.UpdateView):
    model = Load
    template_name = 'edit_price_modal.html'
    form_class = UpdatePriceForm
    success_message = 'Success: Load price was updated.'
    success_url = reverse_lazy('shipper:home')

    def form_valid(self, form):
        obj = form.save(commit=False)
        if obj.status == 'available':
            super().form_valid(form)
            return redirect('shipper:home')
        else:
            messages.error(self.request,
                           'ERROR: It is not possible to edit price because this load is not available anymore')
            return redirect('shipper:home')


class CancelLoadView(generic.DeleteView):
    model = Load
    template_name = 'cancel_load_modal.html'
    success_message = 'Success: Load was canceled.'
    success_url = '/shipper/home/'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        '''
        if self.object.status == 'accepted':
            load = self.object
            email_subject = 'Shipper canceled an accepted load'
            html_message = render_to_string('email_message_load_canceled.html', {'load': load})
            from_email = DEFAULT_FROM_EMAIL
            to_email = [load.carrier.user.email]
            send_mail(email_subject, html_message, from_email, to_email)
        '''
        return self.delete(request, *args, **kwargs)

finalProject/shipper/templates/cancel-load_modal.html
<form method="post" action="">
{% csrf_token %}
    <div class="modal-header">
        <h5 id="myModalLabel">Cancel Load</h5>
    </div>
    <div class="modal-body">
        <p>Are you sure you want to cancel the load?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Dismiss</button>
        <button type="submit" class="delete-btn btn btn-danger">Confirm</button>
    </div>
</form>

finalProject/shipper/templates/cancel_load_modal.html
<form method="post" action="">
    {% csrf_token %}
    <div class="modal-header">
        <h5 id="myModalLabel">Cancel Load</h5>
    </div>
    <div class="modal-body">
        <p>Are you sure you want to cancel the load?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Dismiss</button>
        <button type="submit" class="delete-btn btn btn-danger">Confirm</button>
    </div>
</form>

finalProject/shipper/templates/dashboard.html
{% extends 'base.html' %}

{% block navbar-options %} 
<li><a title="logout" class="logout-popup-button" >Logout</a></li>
{% endblock navbar-options%}

{% block content %}
<br/>

{% if messages %}
<div class="alert alert-success" role="alert">
   <ul class="messages">
      {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
   </ul>
</div>
{% endif %}

<div class="container">
   <div class="row-fluid">
      <div class="span12 main">
         <div class="control-label span3">
            <h3>Posted Loads</h3>
         </div>
         <div class="span2">
            <button class="post-load btn btn-block " type="button" name="button" style="border-radius: 20px;">
            <i class="fas fa-plus-circle"></i>
            Add New
            </button>
         </div>
      </div>
   </div>
</div>

<br/>

<div style="width:80%; margin: 0px auto;">
   <table id="tableShipperLoads" class="table" >
      <thead style="color:white; background-color: #4c4c4c;">
         <tr>
            <th>PICK UP</th>
            <th>REF.#</th>
            <th>ORIGIN</th>
            <th>DESTINATION</th>
            <th>STATUS</th>
            <th>PRICE</th>
            <th></th>
            <th></th>
         </tr>
      </thead>
      <tbody>
         <tr>
            <th colspan=100%>Accepted Loads
            <th>
         </tr>
         {% for load in loads %}
            {% if load.status == 'accepted' %}
            <tr>
                <td>{{ load.pickup_date }}</td>
                <td>{{ load.ref }}</td>
                <td>{{ load.origin_city }}</td>
                <td>{{ load.destination_city }}</td>
                <td>{{ load.status }} by {{load.carrier.user.get_full_name}}</td>
                <td>${{ load.price }}</td>
                <td> </td>
                <td style="text-align: center;"><button type="button" class="btn">
                <i class="far fa-trash-alt"></i> Cancel</button>
                </td>
            </tr>
            {% endif %}
         {% endfor %}
      </tbody>
      <tbody>
         <tr>
            <th colspan=100%>Available Loads</th>
         </tr>
         {% for load in loads %}
            {% if load.status == 'available' %}
            <tr>
                <td>{{ load.pickup_date }}</td>
                <td>{{ load.ref }}</td>
                <td>{{ load.origin_city }}</td>
                <td>{{ load.destination_city }}</td>
                <td>{{ load.status }}</td>
                <td>${{ load.price }}</td>
                <td style="text-align: center;"><button type="button" class="btn ">
                <i class="far fa-edit"></i> Edit Rate</button>
                </td>
                <td style="text-align: center;"><button type="button" class="btn ">
                <i class="far fa-trash-alt"></i> Cancel</button>
                </td>
            </tr>
            {% endif %}
         {% endfor %}
      </tbody>
   </table>
   <br/> <br/> <br/>
</div>

<section>

   <div class="modal fade" tabindex="-1" role="dialog" id="modal">
      <div class="modal-dialog" role="document">
         <div class="modal-content">
         </div>
      </div>
   </div>

   <script type="text/javascript">
      $(document).ready(function() {
          $(".post-load").modalForm({
              formURL: "{% url 'shipper:post_load' %}"
          });
          $(".logout-popup-button").modalForm({
              formURL: "{% url 'account:logout_popup' %}" 
          });
      });
   </script>

</section>

{% endblock content %}

finalProject/shipper/templates/edit-price_modal.html
<form method="post" action="">
    {% csrf_token %}
    <div class="modal-header">
        <h5 id="myModalLabel">Edit Price</h5>
    </div>
    
    <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
    
    {% for field in form %}
      <div class="form-group{% if field.errors %} invalid{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="submit-btn btn btn-primary" data-dismiss="modal">Save</button>
    </div>
</form>

finalProject/shipper/templates/edit_price_modal.html
<form method="post" action="">
    {% csrf_token %}
    <div class="modal-header">
        <h5 id="myModalLabel">Edit Price</h5>
    </div>

    <div class="modal-body">

        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>

        {% for field in form %}
        <div class="form-group{% if field.errors %} invalid{% endif %}">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% for error in field.errors %}
            <div class="alert alert-danger" role="alert">
                <p class="help-block">{{ error }}</p>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="submit-btn btn btn-primary" data-dismiss="modal">Save</button>
    </div>
</form>

finalProject/shipper/templates/email_message_load_canceled.html
{% autoescape off %}

Dear {{ load.carrier.user.get_full_name }},

The following load was CANCELED by {{ load.shipper.user.get_full_name }}:

Pickup Date: {{ load.pickup_date }}
REF. : {{ load.ref }}
Origin City: {{ load.origin_city }}
Destination City: {{ load.destination_city }}
Price: {{ load.price }}

You can check in our website the loads that are available.

Sincerely,
Squad 1
{% endautoescape %}

finalProject/shipper/templates/post-load.html
<form method="post" action="">
    {% csrf_token %}

    <div class="modal-header">
        <div class="row-fluid">
            <div class="span12 main">
                <div class="span6 main">
                    <h4 class="modal-title">Add Load </h4>
                </div>
                <div class="span6 main">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-body">
        <div class="row-fluid">
            <div class="span12 main">
                {% for field in form %}
                <div class="form-group{% if field.errors %} invalid{% endif %}">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% for error in field.errors %}
                    <div class="alert alert-danger" role="alert">
                        <p class="help-block">{{ error }}</p>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="post_load_button" type="button" class="submit-btn btn btn-primary">Post Load</button>
    </div>

</form>

<script>
      var options = { types: ['(cities)'], componentRestrictions: {country: 'us'} };
      var origin_city_autocomplete = new google.maps.places.Autocomplete(document.getElementById('origin_city_id'), options);
      var destination_city_autocomplete = new google.maps.places.Autocomplete(document.getElementById('destination_city_id'), options);
      // calculate distance
        function calculateDistance() {
            var origin = $('#origin_city_id').val();
            var destination = $('#destination_city_id').val();
            if(origin != "" && destination != ""){
                var service = new google.maps.DistanceMatrixService();
                service.getDistanceMatrix(
                    {
                        origins: [origin],
                        destinations: [destination],
                        travelMode: google.maps.TravelMode.DRIVING,
                        unitSystem: google.maps.UnitSystem.IMPERIAL, // miles and feet.
                        avoidHighways: false,
                        avoidTolls: false
                    }, callback);
            } else{
                console.log("origin or destination is empty");
            }
        }
      // get distance results
        function callback(response, status) {
            console.log('callback function')
            if (status != google.maps.DistanceMatrixStatus.OK) {
                $('#suggested_price_id').html(err);
            } else {
                var origin = response.originAddresses[0];
                var destination = response.destinationAddresses[0];
                if (!(response.rows[0].elements[0].status === "NOT_FOUND" ||
                        response.rows[0].elements[0].status === "ZERO_RESULTS")) {
                    console.log(response)
                    var distance = response.rows[0].elements[0].distance;
                    var distance_in_mile = distance.value / 1609.34; // the mile
                    sugestedPrice(distance_in_mile);
                }
            }
        }
      // calculate suggested price
      function sugestedPrice(miles){
        document.getElementById("suggested_price_id").value = (miles * 1.50).toFixed(2);
      }
    google.maps.event.addListener(origin_city_autocomplete, 'place_changed', function() {
        calculateDistance();
    });
    google.maps.event.addListener(destination_city_autocomplete, 'place_changed', function() {
        calculateDistance();
    });

</script>

finalProject/shipper/templates/post_load.html
<form method="post" action="">
    {% csrf_token %}

    <div class="modal-header">
        <div class="row-fluid">
            <div class="span12 main">
                <div class="span6 main">
                    <h4 class="modal-title">Add Load </h4>
                </div>
                <div class="span6 main">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-body">
        <div class="row-fluid">
            <div class="span12 main">
                {% for field in form %}
                <div class="form-group{% if field.errors %} invalid{% endif %}">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% for error in field.errors %}
                    <div class="alert alert-danger" role="alert">
                        <p class="help-block">{{ error }}</p>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="post_load_button" type="button" class="submit-btn btn btn-primary">Post Load</button>
    </div>

</form>

<script>
      var options = { types: ['(cities)'], componentRestrictions: {country: 'us'} };
      var origin_city_autocomplete = new google.maps.places.Autocomplete(document.getElementById('origin_city_id'), options);
      var destination_city_autocomplete = new google.maps.places.Autocomplete(document.getElementById('destination_city_id'), options);
      // calculate distance
        function calculateDistance() {
            var origin = $('#origin_city_id').val();
            var destination = $('#destination_city_id').val();
            if(origin != "" && destination != ""){
                var service = new google.maps.DistanceMatrixService();
                service.getDistanceMatrix(
                    {
                        origins: [origin],
                        destinations: [destination],
                        travelMode: google.maps.TravelMode.DRIVING,
                        unitSystem: google.maps.UnitSystem.IMPERIAL, // miles and feet.
                        avoidHighways: false,
                        avoidTolls: false
                    }, callback);
            } else{
                console.log("origin or destination is empty");
            }
        }
      // get distance results
        function callback(response, status) {
            console.log('callback function')
            if (status != google.maps.DistanceMatrixStatus.OK) {
                $('#suggested_price_id').html(err);
            } else {
                var origin = response.originAddresses[0];
                var destination = response.destinationAddresses[0];
                if (!(response.rows[0].elements[0].status === "NOT_FOUND" ||
                        response.rows[0].elements[0].status === "ZERO_RESULTS")) {
                    console.log(response)
                    var distance = response.rows[0].elements[0].distance;
                    var distance_in_mile = distance.value / 1609.34; // the mile
                    sugestedPrice(distance_in_mile);
                }
            }
        }
      // calculate suggested price
      function sugestedPrice(miles){
        document.getElementById("suggested_price_id").value = (miles * 1.50).toFixed(2);
      }
    google.maps.event.addListener(origin_city_autocomplete, 'place_changed', function() {
        calculateDistance();
    });
    google.maps.event.addListener(destination_city_autocomplete, 'place_changed', function() {
        calculateDistance();
    });
</script>

finalProject/shipper/templates/shipper_home.html
{% extends 'base.html' %}

{% block title %} Shipper's Page {% endblock title %}

{% block navbar-options %}
<li><a title="logout" class="logout-popup-button">Logout</a></li>
{% endblock navbar-options%}

{% block content %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>

<br/>

{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.level_tag}} message" role="alert" style="width:77%; margin: 0px auto;">
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
            {{ message }} <a href="#" class="del-msg">&times;</a>
        </li>
    </div>
    {% endfor %}
{% endif %}

<br/>

<ul class="nav nav-pills table-size" id="pills-tab">
    <li class="active"><a href="#tab1" data-toggle="tab">Available loads</a></li>
    <li><a href="#tab2" data-toggle="tab">Accepted loads</a></li>
    <li><div class="span2 ">
            <button class="post-load btn btn-block btn-success" type="button" name="button" style="border-radius: 20px;">
                <i class="fas fa-plus-circle"></i>
                Add New
            </button>
        </div>
    </li>
</ul>
<div class="tab-content">
    <div class="tab-pane table-size active" id="tab1">
        <table id="tableAvailable" class="table">
            <thead class="table-head">
                <tr>
                    <th>PICK UP</th>
                    <th>REF.#</th>
                    <th>ORIGIN</th>
                    <th>DESTINATION</th>
                    <th>STATUS</th>
                    <th>PRICE</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for load in loads %}
                {% if load.status == 'available' %}
                <tr>
                    <td>{{ load.pickup_date }}</td>
                    <td>{{ load.ref }}</td>
                    <td>{{ load.origin_city }}</td>
                    <td>{{ load.destination_city }}</td>
                    <td>{{ load.status }}</td>
                    <td>${{ load.price|floatformat:2 }}</td>
                    <td style="text-align: center;">
                        <a class="edit-price-popup-btn btn" data-id="{% url 'shipper:edit_price' load.pk %}">
                            <i class="far fa-edit"></i>
                            Edit Price
                        </a>
                    </td>
                    <td style="text-align: center;">
                        <a class="cancel-load-popup-btn btn btn-danger" data-id="{% url 'shipper:cancel_load' load.pk %}">
                            <i class="far fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane table-size" id="tab2">
        <table id="tableAccepted" class="table">
            <thead class="table-head">
                <tr>
                    <th>PICK UP</th>
                    <th>REF.#</th>
                    <th>ORIGIN</th>
                    <th>DESTINATION</th>
                    <th>STATUS</th>
                    <th>PRICE</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for load in loads %}
                {% if load.status == 'accepted' %}
                <tr>
                    <td>{{ load.pickup_date }}</td>
                    <td>{{ load.ref }}</td>
                    <td>{{ load.origin_city }}</td>
                    <td>{{ load.destination_city }}</td>
                    <td>{{ load.status }} by {{load.carrier.user.get_full_name}}</td>
                    <td>${{ load.price|floatformat:2 }}</td>
                    <td></td>
                    <td style="text-align: center;">
                        <a class="cancel-load-popup-btn btn btn-danger" data-id="{% url 'shipper:cancel_load' load.pk %}">
                            <i class="far fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>

<br/>
<br/>


<section>
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(document).ready(function() {
        // Tables
        $('#tableAvailable').DataTable({
            "paging": false,
            "info": false,
            "language": {
                "emptyTable": "There are no available loads"
            }
        });
        $('#tableAccepted').DataTable({
            "paging": false,
            "info": false,
            "language": {
                "emptyTable": "There are no accepted loads"
            }
        });
        // Modals
        $(".post-load").modalForm({
            formURL: "{% url 'shipper:post_load' %}"
        });
        $(".logout-popup-button").modalForm({
            formURL: "{% url 'account:logout_popup' %}"
        });
        $(".edit-price-popup-btn").each(function () {
            $(this).modalForm({formURL: $(this).data('id')});
        });
        $(".cancel-load-popup-btn").each(function () {
            $(this).modalForm({formURL: $(this).data('id')});
        });
        // messages timeout for 10 sec
        setTimeout(function() {
            $('.message').fadeOut('slow');
        }, 10000); // <-- time in milliseconds, 1000 =  1 sec
        // delete message
        $('.del-msg').live('click',function(){
            $('.del-msg').parent().parent().attr('style', 'display:none;');
        })
    });
 </script>



{% endblock content %}